### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/parser#1]
Glad to see this here!
- I'm thinking we should rename the repo to just `parser`
- I have a graphql-dotnet-ci account that can be used with AppVeyor
- I signed up for an open-source myget account a while ago though haven't used it yet
- Is there any special setup needed for AppVeyor?

**Comment by mkmarek** [comment]
- Yeah, I guess it's obvious that it would be a graphql parser when it is in graphql org. :)
- Good! We can use that. It would be also good if you sign up with that account for https://coveralls.io/ so we can also publish code coverage. For publishing I would need an encrypted api key.
- Good, for that I would only need encrypted api key for appveyor.yml file (https://ci.appveyor.com/tools/encrypt) so I can publish packages within the build process.
- Nothing special there. Or not anything that can't be done within appveyor.yml file. But I will have to try it out.  I would only need those two API keys.

Another thing would be publishing to official NuGet.  For that do you propose using the graphql-dotnet-ci account or perhaps one of our accounts?

**Comment by joemcbride** [comment]
* coveralls: OOHuk90+WRWFPhXeTIqUZGigsmFg0xuqkevpunO4ZL4D71LNJH/Qhl0g5gV+Y8Xn

I have been using my personal account for Nuget, though looks like you can add multiple people to a Nuget.  I can sign up the graphql-dotnet-ci account to Nuget.org and we can do both if that works for you.

Working on figuring out the myget situation.

**Comment by joemcbride** [comment]
MyGet
* token: EbuumAanV7HkLSN4xjf0H+cOPHf7aGhgbHFWWpNp7vMh3ewdO6loswPlGZ1fgewh
* feed: https://www.myget.org/F/graphql-dotnet/api/v3/index.json
* publish: https://www.myget.org/F/graphql-dotnet/api/v2/package

**Comment by joemcbride** [comment]
Changed the token for MyGet

**Comment by mkmarek** [comment]
Perfect! I have some personal matters that I have to attend now, but once I'm back at my PC I'll start implementing CI and adding some nice readme file. It seems that I have eveyrthing I need for now. :+1:  

About that nuget thing. If you add the package with your existing account and give me rights for being able to deploy it, that works for me as well. I'll connect it to the appveyor build process.

The flow would be: When you push a commit to the master branch with a version tag, it will generate a new package and deploy it to nuget.

Deployment to myget as opposed to deployment to nuget would work on every commit. No version tag needed.

**Comment by joemcbride** [comment]
Sounds good to me.  I think we should be able to use `GraphQL-Parser` as the NuGet name.

**Comment by mkmarek** [comment]
- [x]  CI through AppVeyor
- [x]  Code coverage
- [x]  MyGet package after every build
- [x]  NuGet package GraphQL-Parser is there and I sent you an invite for ownership. As it seems there is no real difference in who creates the package as every owner can do pretty much anything.
- [x]  All badges in place
- [x]  Readme with some examples
- [ ]  Deploys from CI to Nuget + versioning

Initially I published some packages with a wrong name to that MyGet feed. So just to have it clean I would like to ask you to delete it afterwards. The wrong package is GraphQLParser. Now it creates and publishes packages under name: GraphQL-Parser.

Also after you accept the ownership of the NuGet package, then I'd like to ask you for another encrypted token which would be for the API key so I can connect finish up auto deploys to NuGet.

After this I believe it's all from the initial setup. :)

Thanks!

**Comment by joemcbride** [comment]
Awesome!  I'm traveling today though should be able to get to that tonight.

**Comment by joemcbride** [comment]
Nuget: ZWTuZ9DB3Svu+HDrn4u9hQ0Q9bpXb/waywJplGWDdncs2f2dY3jAdwLvNtNES7qP

Got the other package deleted.

**Comment by joemcbride** [comment]
Closing as this is all setup.
