### ISSUE TITLE
Release v7

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/parser#107]
1. ~Test string -> ROM in GraphQL.NET~ DONE
2. ~Update README.md~ DONE
3. ~Describe new option for ignoring comments.~ DONE in #101
4. ~XML comments~ PARTIALLY DONE
5. ~Take care of #89~ DONE

**Comment by sungam3r** [comment]
@Shane32 The main problem with v7 in GraphQL.NET is that new ROM APIs destroy familiar string-based interfaces and approaches.

**Comment by sungam3r** [comment]
@Shane32 Are we ready to release v7?

**Comment by Shane32** [comment]
As far as I know, but let’s release it alongside v4

**Comment by sungam3r** [comment]
Done in https://github.com/graphql-dotnet/parser/releases/tag/7.0.0
