### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by Tornhoof** [graphql-dotnet/parser#12]
Hi,
I migrated your parser to VS2017 and noticed a very low hanging performance fruit you might want, I can't provide a pull request, as my branch is already too different, because all those VS2017 changes require quite a bit of change.
Anyway:
In LexerContext.GetToken() you currently have the following line 31:
```csharp
var unicode = this.IfUnicodeGetString();
```
This line is only used in the error case, but processed each and every time.
If you move it down to the exception, your benchmark runs ~6 times faster and uses ~5 less memory.
```csharp
throw new GraphQLSyntaxErrorException($"Unexpected character {ResolveCharName(code, IfUnicodeGetString())}", source, currentIndex);
```
All your unit tests still work obviously, because ``IfUnicodeGetString()`` does not change ``currentIndex``.
The change itself is here:
https://github.com/Tornhoof/graphql-dotnet-parser/commit/50f5b6dca69dc7f849a54ff4a5bba254a51b6d1f

Benchmark before:

``` ini

BenchmarkDotNet=v0.10.8, OS=Windows 10 Redstone 2 (10.0.15063)
Processor=Intel Core i7-4790K CPU 4.00GHz (Haswell), ProcessorCount=8
Frequency=3906243 Hz, Resolution=256.0005 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.7.2098.0
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.7.2098.0


```
 |         Method |     Mean |    Error |   StdDev |   Gen 0 | Allocated |
 |--------------- |---------:|---------:|---------:|--------:|----------:|
 | LexKitchenSink | 84.97 us | 1.506 us | 1.335 us | 18.9209 |  77.77 KB |

Benchmark after:
``` ini

BenchmarkDotNet=v0.10.8, OS=Windows 10 Redstone 2 (10.0.15063)
Processor=Intel Core i7-4790K CPU 4.00GHz (Haswell), ProcessorCount=8
Frequency=3906243 Hz, Resolution=256.0005 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.7.2098.0
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.7.2098.0


```
 |         Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
 |--------------- |---------:|----------:|----------:|-------:|----------:|
 | LexKitchenSink | 13.89 us | 0.0297 us | 0.0232 us | 3.5553 |   14.6 KB |

Unfortunately that's basically the only really low hanging performance fruit, everything else is mostly related to substring etc. and for that quite a few more changes are necessary.

**Comment by joemcbride** [comment]
Got this added.  I also got the project updated to VS2017.  Thanks!
