### ISSUE TITLE
Use string.GetHashCode in ROM

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/parser#191]
https://docs.microsoft.com/en-us/dotnet/api/system.memoryextensions.equals?view=net-6.0#system-memoryextensions-equals(system-readonlyspan((system-char))-system-readonlyspan((system-char))-system-stringcomparison)

https://docs.microsoft.com/en-us/dotnet/api/system.string.gethashcode?view=net-6.0#system-string-gethashcode(system-readonlyspan((system-char)))

Should both be faster than existing implementations.  Need IFDEF check for both.

**Comment by Shane32** [comment]
MemoryExtensions.Equals just calls SequenceEqual, so no need to use that.

**Comment by Shane32** [comment]
However, the GetHashCode method looks to be extremely optimized and a good hash.  See this "Marvin" class which is used by the method:

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Marvin.cs

**Comment by sungam3r** [comment]
As I said it does not work. See `MemoryTests.GetHashCode_Issue` . Both `net5`/`net6` tests failed. Such implementation of hash is simply not suitable for our purposes. 
`"abcabc".AsMemory().Slice(0, 3).GetHashCode()` should be equal to `"abcabc".AsMemory().Slice(3, 3).GetHashCode()` Otherwise, all dictionaries with ROM keys in GraphQL.NET are stopped working correctly.

**Comment by sungam3r** [comment]
See #203

**Comment by Shane32** [comment]
> As I said it does not work. See `MemoryTests.GetHashCode_Issue` . Both `net5`/`net6` tests failed. Such implementation of hash is simply not suitable for our purposes. `"abcabc".AsMemory().Slice(0, 3).GetHashCode()` should be equal to `"abcabc".AsMemory().Slice(3, 3).GetHashCode()` Otherwise, all dictionaries with ROM keys in GraphQL.NET are stopped working correctly.

I understand.  The suggestion here is to use `string.GetHashCode`, not `ReadOnlyMemory.GetHashCode`.  It is only available on .NET 6.

`string.GetHashCode("abcabc".AsMemory().Slice(0, 3).Span)` equals `string.GetHashCode("abcabc".AsMemory().Slice(3, 3).Span)`

**Comment by sungam3r** [comment]
🤦 done
