### ISSUE TITLE
Parser.Parse throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Metalnem** [graphql-dotnet/parser#21]
**Parser.Parse** throws an **ArgumentOutOfRangeException** when parsing the file from the [attached archive]. You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
var text = File.ReadAllText(path);
var parser = new Parser(new Lexer());
parser.Parse(new Source(text));
```

Found via [SharpFuzz].

[attached archive]: https://github.com/graphql-dotnet/parser/files/2707107/ArgumentOutOfRangeException.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by sungam3r** [comment]
I can not read the file from the archive. It looks like it has binary data.

**Comment by sungam3r** [comment]
I apologize, confused the file with a similar one from another issue. The error was that it was not possible to read the unicode character at the end of the file.
