### ISSUE TITLE
Parser.Parse takes around 18s to parse the 58K file

### ISSUE THREAD

**Issue by Metalnem** [graphql-dotnet/parser#22]
**Parser.Parse** takes around 18s to parse the 58K file from the [attached archive]. You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
var text = File.ReadAllText(path);
var parser = new Parser(new Lexer());
parser.Parse(new Source(text));
```

Found via [SharpFuzz].

[attached archive]: https://github.com/graphql-dotnet/parser/files/2707111/Test.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by sungam3r** [comment]
I can not read the file from the archive. It looks like it has binary data.

**Comment by sungam3r** [comment]
Oh, I get it. The whole point is that the file is binary and its parsing error occurs. Time is wasted on getting an error message in [this method](https://github.com/graphql-dotnet/parser/blob/master/src/GraphQLParser/Exceptions/GraphQLSyntaxErrorException.cs#L55), which makes numerous extremely inefficient string replacement calls.

**Comment by sungam3r** [comment]
My explanation was incorrect. The point is not even in allocations, but in the fact that the iterator for each character in the source line called `Replace` method, which in turn again ran over the entire line. In any case, now there are no such problems.
