### ISSUE TITLE
Don't track branch coverage for Debug.Assert

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/parser#231]
![изображение](https://user-images.githubusercontent.com/21261007/152432815-59d328f6-75a1-4e4d-8d9a-8149df5e2eb9.png)

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test:
![изображение](https://user-images.githubusercontent.com/21261007/152432885-a968d5e8-fb95-4311-a52f-2c9c91e720ef.png)

![изображение](https://user-images.githubusercontent.com/21261007/152432955-5333e316-5e32-4da5-98d3-61f8b4bc793d.png)

@Shane32 So may be add `-c Release` to increase coverage. `Debug.Assert` never happens when code works well so those calls always decrease coverare :)

**Comment by Shane32** [comment]
I wouldn’t make this change just to increase a statistic. The stack traces from failures will be less accurate in release and the whole point of the assert is to verify the code is working right. By testing in release the assert is useless. I most certainly definitely would not test in release.

**Comment by sungam3r** [comment]
OK. Here it is - https://github.com/coverlet-coverage/coverlet/issues/258

**Comment by sungam3r** [comment]
@Shane32 Single uncovered line left in `LexerContext.cs` besides this `Debug.Assert()`
![изображение](https://user-images.githubusercontent.com/21261007/153471654-a83d2ac8-3c8a-45c5-a49e-53dab60d07d9.png)

Could you help with `ReadBlockString`?
