### ISSUE TITLE
Package compatibility issues 

### ISSUE THREAD

**Issue by corruptmem** [graphql-dotnet/parser#28]
We've been having issues with occasional bad builds of our graphql-dotnet based being generated, where a bad build will always output the following exception for all GraphQL calls:

```
ExecutionErrors [GraphQL.ExecutionError: Unmapped selection Field ---> GraphQL.ExecutionError: Unmapped selection Field
   at GraphQL.Language.CoreToVanillaConverter.Selection(ASTNode source)
   at GraphQL.Language.CoreToVanillaConverter.<>c__DisplayClass10_0.<SelectionSet>b__0(ASTNode s)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Language.CoreToVanillaConverter.SelectionSet(GraphQLSelectionSet source)
   at GraphQL.Language.CoreToVanillaConverter.Operation(GraphQLOperationDefinition source)
   at GraphQL.Language.CoreToVanillaConverter.<>c__DisplayClass3_0.<AddDefinitions>b__0(ASTNode def)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Language.CoreToVanillaConverter.Convert(String body, GraphQLDocument source)
   at GraphQL.Execution.GraphQLDocumentBuilder.Build(String body)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
```

Looking at the [source of that exception](https://github.com/graphql-dotnet/graphql-dotnet/blob/087906ce5268cab787ebb289546d629ca14d525e/src/GraphQL/Language/CoreToVanillaConverter.cs#L144) it should never be throwing that exception when ``source.Kind == ASTNodeKind.Field``.

Having done some digging, I am pretty sure I understand the problem now:

Our project depends (via graphql-dotnet) on GraphQL-Parser 3.0.0, and each time our CI build runs, it pulls a new copy of GraphQL-Parser 3.0.0 from nuget. 

What is happening is that sometimes (maybe 5-10% of the time) the package being served by NuGet has ``ASTNodeKind.Field == 7``, and the rest of the time ``ASTNodeKind.Field == 6``. 

It would appear that 13 days ago de9ffa21f396c621b4e9e134c640d4187f4ef60a added a new  ``ASTNodeKind.Comment`` as the first field in the enum, which has shifted the int value of everything below it up by one, breaking binary compatibility. 

At least [one other person on StackOverflow](https://stackoverflow.com/questions/55442634/graphql-for-net-error-unmapped-selection-field) appears to be hitting this issue, but I'm assuming most people won't notice because they have a cached 3.0.0 nuget package.

So I think there are two issues here:

- Was the current pre-release version mistakenly pushed to nuget as 3.0.0 at some point? Because NuGet appears to be intermittently serving a different version as 3.0.0. Perhaps the incorrect package got onto NuGet's CDNs? We wrote a script to repeatedly pull the package from NuGet and confirmed that it was occasionally serving an incorrect version of the package.

- Renumbering ASTNodeKind is a breaking change - the major version number should probably be incremented so a package doesn't get incorrectly upgraded from 3.0 to 3.1 and break in a very confusing way. Maybe it would be better to move the new Comment enum field to the bottom of the list instead rather than renumbering all existing enum fields?

Thanks!

**Comment by joemcbride** [comment]
The version on nuget.org has not been updated.  Are you perhaps pointed to the myget.org feed?  That one may have been updated.

**Comment by sungam3r** [comment]
Oh, I really did not notice this moment with the enumeration element. These were changes from another PR. Obviously, backward compatibility is broken when pasting the first value.

**Comment by BenjaBobs** [comment]
Hi, so I recently ran into this problem without having updated anything, but simply by installing on a new computer. I think you might have updated the code in graphql-parser without updating the version number, because the 3.0.0 dll on my old computer does not contain commit https://github.com/graphql-dotnet/parser/commit/290c718863907b62f728c599b467faaf4fc5a8d2 , while the one on the fresh install does. Since both are using an old version of graphql-dotnet that does not expect commit https://github.com/graphql-dotnet/parser/commit/290c718863907b62f728c599b467faaf4fc5a8d2 , this crashes on the new computer.

**Comment by sungam3r** [comment]
@BenjaBobs Can you update parser to 4.1.1 ?

**Comment by BenjaBobs** [comment]
Unfortunately not since I can't update my other GraphQL dependencies yet, which would be the real solution. I guess this is more of a request to get some automatic versioning going so we won't run into mismatches again.

**Comment by sungam3r** [comment]
> Unfortunately not since I can't update my other GraphQL dependencies yet

As far as I know you can just bump parser version. No need to bump other  packages.
