### ISSUE TITLE
More Parse methods

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/parser#296]
Just a note - it seems that we could make more methods public to allow parse concrete parts of document.

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/parser/pull/295#discussion_r1168035018_

**Comment by Shane32** [comment]
See:
- #298

**Comment by Shane32** [comment]
Public `Parse<T>` has been added; just needs someone to add a few lines of code for each `ASTNode` type, which will not change external API but will add functionality.

**Comment by sungam3r** [comment]
Also add tests to cover all cases. I'm not sure there will be no issues. + deprecate non-generic `Parse` method, I think.

**Comment by Shane32** [comment]
I would not deprecate non-generic `Parse` method, but we could just `=> Parse<GraphQLDocument>(...)`

The library's primary purpose is to parse GraphQL documents; all other types are niche cases.

**Comment by sungam3r** [comment]
I'm fine either way.
