### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/parser#3]
Just thinking about the namespace change.  I did like the `GraphQL(Core).Language` as the root namespace.  Thoughts on changing that back to `GraphQL.Language` or `GraphQLCore.Language`?

**Comment by randyridge** [comment]
I'm a fan of graphql.language and integrating it back into the main project if the other fella is ok with it

**Comment by deinok** [comment]
I would like GraphQL.Parser  , to be more close to the other namespaces of the framework

**Comment by sungam3r** [comment]
Is this question still relevant?

**Comment by sungam3r** [comment]
@joemcbride Is this question still relevant? Is it worth making a part of #53 or should we just close this issue?

**Comment by sungam3r** [comment]
Closed due to inactivity.
