### ISSUE TITLE
4.0.0 stable release on nuget.org

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/parser#30]
Maybe it's time for stable 3.1.0 release?

**Comment by joemcbride** [comment]
Due to some of the other changes I think this will require a bump to 4.0.

**Comment by sungam3r** [comment]
Ok. Is this acceptable?

**Comment by joemcbride** [comment]
4.0 is now published on nuget: https://www.nuget.org/packages/GraphQL-Parser/4.0.0
