### ISSUE TITLE
9.0.1 formatting - lost indentation of arguments (fine in 8.x)

### ISSUE THREAD

**Issue by nightroman** [graphql-dotnet/parser#311]
9.0.1 fixes some formatting issues -- https://github.com/graphql-dotnet/parser/issues/287
And introduces a new issue, lost indentation of field arguments.

Please find attached the project for reproducing the issue:
[TryGraphQLParser.zip](https://github.com/graphql-dotnet/parser/files/11292678/TryGraphQLParser.zip)

**Steps**

`x1-type.graphql` was produced by 8.x formatting.
See expected indented arguments:

```graphql
type Query {
  "Fetches an object given its ID."
  node(
    "ID of the object."
    id: ID!): Node
  "Lookup nodes by a list of IDs."
  nodes(
    "The list of node IDs."
    ids: [ID!]!): [Node]!
```

Run

    dotnet run -- x1-type.graphql

This produces the new `x1-type.graphql.output.graphql`.
See unexpected not indented arguments:

```graphql
type Query {
  "Fetches an object given its ID."
  node(
  "ID of the object."
  id: ID!): Node
  "Lookup nodes by a list of IDs."
  nodes(
  "The list of node IDs."
  ids: [ID!]!): [Node]!
```

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/GraphQL-Parser/9.0.2

**Comment by sungam3r** [comment]
Also see #314, I didn't fix all issues yet but the whole process does not seem difficult now.
