### ISSUE TITLE
Support for descriptions

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/parser#33]
So 4.0 added support for comments but it seems that comments should be ignored by the parser. Descriptions are what the spec uses for documentation. More here https://github.com/graphql/graphql-js/pull/927 and here https://graphql.github.io/graphql-spec/June2018/#sec-Descriptions

**Comment by sungam3r** [comment]
Relates to graphql/graphql-spec#420

**Comment by pekkah** [comment]
I have since implemented a new parser which handles the descriptions correctly so this is not an issue for me anymore. Please reopen if you want to track this as a feature request.

**Comment by sungam3r** [comment]
Yes, I want to track this issue.

**Comment by prowe** [comment]
We are also running into this issue, what would the steps be in adding support for this?

**Comment by sungam3r** [comment]
Just as usual - PR, review, merge, publish, update dependent projects.

**Comment by sungam3r** [comment]
Also see #124 :
```
var schema = Schema.For(@"""Root type for all queries""
type Query {
  ""Documentation for the field""
  name: String
}");
```

**Comment by Shane32** [comment]
@sungam3r At a minimum, we should ignore description fields, even if for a later version we actually parse them.  I would say this should be done for 4.0 if we have the time.  (Ok to release 4.0 now though; this can always just be an updated version of the parser engine, and we can release 4.0.1 to use the new parser.)

**Comment by sungam3r** [comment]
Support for descriptions was added in https://github.com/graphql-dotnet/parser/pull/132
