### ISSUE TITLE
Inconsistent formatting of arguments

### ISSUE THREAD

**Issue by nightroman** [graphql-dotnet/parser#330]
Please find attached the project for reproducing the issue and follow the below steps.
[TryGraphQLParser.zip](https://github.com/graphql-dotnet/parser/files/11890307/TryGraphQLParser.zip)

**Steps**

`x1-type.graphql` is the input file to be formatted

```graphql
type DesPcb {
  designItems("An optional array of designators to search." designators: [String!] "Returns the first _n_ elements from the list." first: Int "Returns the elements in the list that come after the specified cursor." after: String "Returns the last _n_ elements from the list." last: Int "Returns the elements in the list that come before the specified cursor." before: String where: DesDesignItemFilterInput): DesDesignItemConnection
}
```

Run

    dotnet run -- x1-type.graphql

This produces the new `x1-type.graphql.output.graphql`.
The field arguments are formatted mostly as expected:

```graphql
type DesPcb {
  designItems(
    "An optional array of designators to search."
    designators: [String!],
    "Returns the first _n_ elements from the list."
    first: Int,
    "Returns the elements in the list that come after the specified cursor."
    after: String,
    "Returns the last _n_ elements from the list."
    last: Int,
    "Returns the elements in the list that come before the specified cursor."
    before: String, where: DesDesignItemFilterInput): DesDesignItemConnection
}
```

But the last argument `where: DesDesignItemFilterInput` formatting is inconsistent, it is expected to be on its own line:

```graphql
type DesPcb {
  designItems(
    "An optional array of designators to search."
    designators: [String!],
    "Returns the first _n_ elements from the list."
    first: Int,
    "Returns the elements in the list that come after the specified cursor."
    after: String,
    "Returns the last _n_ elements from the list."
    last: Int,
    "Returns the elements in the list that come before the specified cursor."
    before: String,
    where: DesDesignItemFilterInput): DesDesignItemConnection
}
```

**Comment by Shane32** [comment]
@sungam3r can you look at this?

**Comment by sungam3r** [comment]
Oh, one more formatting issue 🤦‍♂️ . OK, but no exact timeline.

**Comment by sungam3r** [comment]
@nightroman I think this is not a bug but a decision by design. Argument has its own line only if it has comment or description. 

Options:
1. There should be an option like existing `EachDirectiveLocationOnNewLine` - maybe `EachArgumentDefinitionOnNewLine`. This option will force all argument of all fields of all types to be printed on its own lines.
2. Print all arguments of particular field on new line if at least one argument should be printed on its own line (comment or description exists).
3. Other suggestions?

**Comment by nightroman** [comment]
The design might be questionable... but it is what it is, you might know all the reasons better.
Formatting standards are often opinionated and the known source of holy wars :)
Options looks like a reasonable way to make clients happy.

**Comment by nightroman** [comment]
> @nightroman Also try to remove description from some other field, for example, `after`.

Just to see what happens or to "fix/adjust" formatting?

I do not really want to use descriptions (add/remove) in order to adjust formatting. Besides, we do not always author descriptions, some of them are generated. E.g. in the provided example only `designators` description is "ours". Others, including missing are generated or not generated by HotChocolate that we use for building our GQL.

**Comment by sungam3r** [comment]
> Just to see what happens or to "fix/adjust" formatting?

Just to see what happens.

I provided some options above. Do you have suggestions?

**Comment by Shane32** [comment]
I’d suggest option 2 for default behavior. Options would be good also of course.

**Comment by nightroman** [comment]
> I’d suggest option 2 for default behavior. Options would be good also of course.

This looks reasonable to me as well.

**Comment by sungam3r** [comment]
OK, I'll go on with option 2.

**Comment by sungam3r** [comment]
#358 combines all options

**Comment by nightroman** [comment]
Awesome! When is the new nuget update expected, approximately? Look forward trying this.

**Comment by sungam3r** [comment]
After #359 and maybe soon after some changes around #360

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/parser/releases/tag/9.3.0

**Comment by nightroman** [comment]
@Shane32 @sungam3r Thank you, I have tried 9.3.0, it works exactly as expected!
