### ISSUE TITLE
Сomments are shuffled in the schema

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/parser#35]
Unfortunately, we forgot to read the comment in one of the `ParserContext` methods - `ParseEnumValueDefinition`. Because of this, the comments stack fills up and the following items take previous comments from it. As a result, the scheme turns into a mess. It was fun to watch it in our production apps. At first we thought it was our mistake ).

**Comment by joemcbride** [comment]
@sungam3r `4.1.1` is published to Nuget.org, may take a bit to index.

https://www.nuget.org/packages/GraphQL-Parser/4.1.1
