### ISSUE TITLE
Comments should have no significance to the semantic meaning

### ISSUE THREAD

**Issue by almazik** [graphql-dotnet/parser#69]
Current parser tries to associate comments with the entities by assuming that the comment preceding the definition belongs to that definition.

According to the [specification draft](https://spec.graphql.org/draft/#Comment):
> Comments are Ignored like white space and may appear after any token, or before a LineTerminator, and have no significance to the semantic meaning of a GraphQL Document.

So we should interpret comments just like the whitespace, skipping them during lex parsing.

This issue relates to #33 as documentation should replace the current comments annotation logic

**Comment by sungam3r** [comment]
I just have to note that this is just a draft specification requirement. So for now, support for this feature can wait a bit..

**Comment by almazik** [comment]
Agree that it _may_ wait, but for example HotChocolate and all graphql syntax highlighting plugins I've used already support it.

I've started implementing #33, as we might have to just switch to HotChocolate otherwise. 

As a side note (which may be extracted into a separate issue), the current parsing logic doesn't seem to match the structure of the spec. I don't know if it's due to the historical development reasons, or the GraphQL spec have evolved quite far, but I think it would be great to refactor the parser to match the [structure of the specification](http://spec.graphql.org/draft/#sec-Document-Syntax). For example (as defined in the spec):
Document has a list of Definitions.
Definition is either ExecutableDefinition, TypeSystemDefinition or TypeSystemExtension.
ExecutableDefinition is either an OperationDefinition or FragmentDefinition. 
etc. What do you think?

**Comment by sungam3r** [comment]
> Document has a list of Definitions.
Definition is either ExecutableDefinition, TypeSystemDefinition or TypeSystemExtension.
ExecutableDefinition is either an OperationDefinition or FragmentDefinition.
etc.

The structure of the parser document is the same, isn't it?

**Comment by Shane32** [comment]
The current 2018 spec says the same thing about comments, by the way, that they are treated as white space. This seems like an important fix

**Comment by sungam3r** [comment]
Fixed by #105 ?

**Comment by Shane32** [comment]
Yes (optional). Also see #104 and #80

**Comment by Shane32** [comment]
Also see https://github.com/graphql-dotnet/parser/pull/101#discussion_r559053359
