### ISSUE TITLE
Reading a schema file that has triple quotes?

### ISSUE THREAD

**Issue by gregarican** [graphql-dotnet/parser#81]
So I have a schema file. With comments encased in triple quotes. Trying to read in the file like this:
` var schemaTxt = File.ReadAllText(@".\shopify.graphql");
            var schema = Schema.For(schemaTxt); `
When I do so the first line with triple quotes is throwing an exception. Is there an option I can configure to treat these as comments and ignore them?

For example, """Marks an element of a GraphQL schema as having restricted access."""

**Comment by sungam3r** [comment]
Possible duplicate of #33.

**Comment by sungam3r** [comment]
Support for descriptions was added in #132
