### ISSUE TITLE
Is there a list of allowable AST node types for each container?

### ISSUE THREAD

**Issue by StingyJack** [graphql-dotnet/parser#95]
Like what ASTNodeKind are permitted in a GraphQlDocument.Definitions collection? What can be in a SelectionSet collection? And so on.

**Comment by sungam3r** [comment]
You can find complete grammar [here](http://spec.graphql.org/June2018/#sec-Appendix-Grammar-Summary.Document).

**Comment by StingyJack** [comment]
Thanks!
